### ISSUE TITLE
requirements.txt missing in PyPI source release

### ISSUE THREAD

**Issue by BastianZim** [aws/amazon-codeguru-profiler-python-agent#13]
Hi,

the setup.py file currently gets the necessary requirements from requirements.txt as specified here: 
https://github.com/aws/amazon-codeguru-profiler-python-agent/blob/ea6a2f1f8ee17da83425bc811afa8dd86d60625d/setup.py#L7

This is not included with the [source release](https://files.pythonhosted.org/packages/a1/89/ab6a5007ebce2c1f35ec947b38c9379b07bebe33f72dfb4f3415590ddf96/codeguru_profiler_agent-1.0.2.tar.gz) in [PyPI](https://pypi.org/project/codeguru-profiler-agent/#files) which makes building from source impossible.

Would it be possible to include that again to be able to build without using the wheel? 

I noticed this because I maintain the conda-forge feedstock for this and it was caught in our CI, as can be seen here: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=278441&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d

Edit: This has was caught in the CI but I was able to verify this locally as well.

**Comment by gimki** [comment]
Released

**Comment by BastianZim** [comment]
Thanks
