### ISSUE TITLE
Congrats 🎉 

### ISSUE THREAD

**Issue by ivoanjo** [aws/amazon-codeguru-profiler-python-agent#9]
Just wanted to say hi! It's really awesome to see this codebase out in the public, big congrats!
I still see some of my mistakes in it -- I won't tell you where, to make it interesting xD

Hope everything's going well with the team. Hoping to see the Java agent out in public as well!

Let the best agent and product win ;)

**Comment by isaac-jordan** [comment]
Thanks Ivo! Best of luck with everything.
